import React from 'react'
import { useDispatch } from 'react-redux'
//import foodItemService from '../services/foodItem'
import { addFooditem } from '../reducers/fooditemReducer'

/*
foodItem: {
  name: String,
  protein: Number,
  fat: Number,
  carbohydrate: Number,
  id: String (generated by db)
}
*/
const FooditemForm = () => {
  const dispatch = useDispatch()

  const handleAddFoodItem = (event) => {
    event.preventDefault()
    console.log('Adding food item', event.target.name.value)

    const foodItem = {
      name: event.target.name.value,
      protein: event.target.protein.value,
      fat: event.target.fat.value,
      carbohydrate: event.target.carb.value
    }
    dispatch(addFooditem(foodItem))
  }

  return (
    <div>
      <h2>Create Food Item</h2>
      <form onSubmit={handleAddFoodItem}>
        <table><tbody>
          <tr>
            <td>Food name</td><td><input name='name'/></td>
          </tr><tr>
            <td>Protein</td><td><input name='protein' /> per 100g</td>
          </tr><tr>
            <td>Carbohydrates</td><td><input name='carb'/> per 100g</td>
          </tr><tr>
            <td>Fat</td><td><input name='fat'/> per 100g</td>
          </tr>
        </tbody></table>
        <button type='submit'>Add new foodItem</button>
      </form>
    </div>
  )
}

export default FooditemForm