import { Button, Card, CardContent, Grid, Stack, TextField, Typography } from '@mui/material'
import React from 'react'
import { useDispatch } from 'react-redux'
//import foodItemService from '../services/foodItem'
import { addFooditem, createFooditem } from '../reducers/fooditemReducer'
import { createNotification } from '../reducers/notificationReducer'
import fooditemService from '../services/fooditem'

/*
foodItem: {
  name: String,
  protein: Number,
  fat: Number,
  carbohydrate: Number,
  id: String (generated by db)
}
*/
const FooditemForm = () => {
  const dispatch = useDispatch()

  const handleAddFoodItem = async (event) => {
    event.preventDefault()
    console.log('Adding food item', event.target.food.value)

    const foodItem = {
      name: event.target.food.value,
      protein: event.target.protein.value,
      fat: event.target.fat.value,
      carbohydrate: event.target.carb.value
    }
    const returnValue = await dispatch(addFooditem(foodItem))
    if (returnValue != null) {
      //reducer encountered an error and returned it
      //console.log('Error creating fooditem:', returnValue.response.data.error)
      dispatch(createNotification(returnValue.response.data.error))
      //@TODO: Add to error notification window

    }

  }
  return (
    <Grid item xl={4} lg={4} md={6} sm={8} xs={12} >
      <Card variant='outlined'>
        <CardContent>
          <Typography variant='h5'>
              Create fooditem
          </Typography>
          <form onSubmit={handleAddFoodItem}>
            <Stack direction='column' spacing={1} >
              <TextField name='food' id='food-name' variant='outlined' label='Food name' />
              <TextField name='carb' type='number' id='carbs' variant='outlined' label='Carbohydrates (per 100g)' />
              <TextField name='fat' type='number' id='fat' variant='outlined' label='Fat (per 100g)' />
              <TextField name='protein' type='number' id='protein' variant='outlined' label='Protein (per 100g)' />
              <Button variant='contained' type='submit'>Create</Button>
            </Stack>
          </form>
        </CardContent>
      </Card>
    </Grid>
  )
}

export default FooditemForm
