POST http://localhost:3003/api/recipes
content-type: application/json

{
  "title": "Rice and Beans 9",
  "template": "true",
  "ingredients": [
    {
      "fooditemId": "6160686d78c57517d2d6256f",
      "amount": "210",
      "amountUnit": "g",
    },
    {
      "fooditemId": "61606a165ed3db7ba9cd1785",
      "amount": "10",
      "amountUnit": "g",
    },
    {
      "fooditemId": "61606a0b5ed3db7ba9cd1783",
      "amount": "12",
      "amountUnit": "g",
    }
  ]
}
